[variables]
NODE_VERSION = "20.18.0"

[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]

[phases.build]
cmds = [
    "npm cache clean --force",
    "npm install --force",
    "npm run build"
]

[phases.start]
cmd = "npm run preview -- --host 0.0.0.0 --port $PORT"